print("Welcome to your Band Name Generator.")
city = input("What city were you born?\n")
print(city)
pet = input("What Name would you give your pet?\n")
print(pet)
print("Your Band Name Suggestion is: " + city + " " +pet)
print("Thank you for trusting us!")
